apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix-app
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  template:
    metadata:
      name: netflix
      labels:
        app: netflix-app
    spec:
      containers:
        - name: netflix
          image: gopi8234/Netflix:latest
          ports:
            - containerPort: 80
              name: netflix
              protocol: "TCP"